"""drop_out_of_stock

Revision ID: 034c64c3c71d
Revises: 7fdb07fbba0e
Create Date: 2026-06-18 12:29:20.945509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034c64c3c71d'
down_revision: Union[str, None] = '7fdb07fbba0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'out_of_stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('out_of_stock', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
