"""add_featured_and_category_image

Revision ID: 5fd7dd6e38f0
Revises: f7e8d9c0b1a2
Create Date: 2026-07-14 09:37:30.077703

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5fd7dd6e38f0'
down_revision: str | None = 'f7e8d9c0b1a2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_entries_id'), 'rate_limit_entries', ['id'], unique=False)
    op.create_index(op.f('ix_rate_limit_entries_key'), 'rate_limit_entries', ['key'], unique=False)
    op.add_column('categories', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('featured', sa.Boolean(), nullable=True))
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('products', 'variants',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('stores', 'working_days',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'1,2,3,4,5,6,7'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'working_days',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'1,2,3,4,5,6,7'"))
    op.alter_column('products', 'variants',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_column('products', 'featured')
    op.drop_column('categories', 'image_url')
    op.drop_index(op.f('ix_rate_limit_entries_key'), table_name='rate_limit_entries')
    op.drop_index(op.f('ix_rate_limit_entries_id'), table_name='rate_limit_entries')
    op.drop_table('rate_limit_entries')
    # ### end Alembic commands ###
