"""add_plan_superadmin

Revision ID: a73ca165b91e
Revises: b2c3d4e5f6a7
Create Date: 2026-06-25 10:01:56.023515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a73ca165b91e'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('plan', sa.String(length=20), nullable=True))
    op.add_column('stores', sa.Column('plan_expires_at', sa.DateTime(), nullable=True))
    op.add_column('stores', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('stores', sa.Column('is_superadmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'is_superadmin')
    op.drop_column('stores', 'is_active')
    op.drop_column('stores', 'plan_expires_at')
    op.drop_column('stores', 'plan')
    # ### end Alembic commands ###
