"""add page_views whatsapp_clicks payment_transactions

Revision ID: c59174683330
Revises: c1b54c3d5f55
Create Date: 2026-07-01 22:05:51.237988

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c59174683330'
down_revision: str | None = 'c1b54c3d5f55'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_views_id'), 'page_views', ['id'], unique=False)
    op.create_index(op.f('ix_page_views_store_id'), 'page_views', ['store_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('mp_preference_id', sa.String(length=100), nullable=True),
    sa.Column('mp_payment_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mp_payment_id'),
    sa.UniqueConstraint('mp_preference_id')
    )
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_store_id'), 'payment_transactions', ['store_id'], unique=False)
    op.create_table('whatsapp_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('cart_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_clicks_id'), 'whatsapp_clicks', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_clicks_store_id'), 'whatsapp_clicks', ['store_id'], unique=False)
    op.drop_index('ix_categories_store_id', table_name='categories')
    op.drop_index('ix_products_category_id', table_name='products')
    op.drop_index('ix_products_store_id', table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_products_store_id', 'products', ['store_id'], unique=False)
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.create_index('ix_categories_store_id', 'categories', ['store_id'], unique=False)
    op.drop_index(op.f('ix_whatsapp_clicks_store_id'), table_name='whatsapp_clicks')
    op.drop_index(op.f('ix_whatsapp_clicks_id'), table_name='whatsapp_clicks')
    op.drop_table('whatsapp_clicks')
    op.drop_index(op.f('ix_payment_transactions_store_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_page_views_store_id'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_id'), table_name='page_views')
    op.drop_table('page_views')
    # ### end Alembic commands ###
